# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/FADD/FADD.xci
# IP: The module: 'FADD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/FADD/FADD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FADD'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/FADD/FADD.xci
# IP: The module: 'FADD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/FADD/FADD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FADD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
