# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/is_mem/is_mem.xci
# IP: The module: 'is_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/is_mem/is_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'is_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/is_mem/is_mem.xci
# IP: The module: 'is_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/projects/Final-CPU/Final-CPU.srcs/sources_1/ip/is_mem/is_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'is_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
